CREATE TABLE [ods].[SFDC_Opportunity_Task_Pivot]
(
[FirstActivityDate] [date] NULL,
[LastActivityDate] [date] NULL,
[LastActivityType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpportunityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StageName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerName] [nvarchar] (121) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[4] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[5] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[6] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[7] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[8] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[9] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[11] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[12] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[13] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[14] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[16] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[17] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[18] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[19] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[20] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[21] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[22] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[23] [nvarchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
