CREATE TABLE [prodcopystg].[Task]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WhoId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhatId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityDate] [date] NULL,
[Status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHighPriority] [bit] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClosed] [bit] NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsArchived] [bit] NULL,
[CallDurationInSeconds] [int] NULL,
[CallType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallDisposition] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallObject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReminderDateTime] [datetime] NULL,
[IsReminderSet] [bit] NULL,
[RecurrenceActivityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRecurrence] [bit] NULL,
[RecurrenceStartDateOnly] [date] NULL,
[RecurrenceEndDateOnly] [date] NULL,
[RecurrenceTimeZoneSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceInterval] [int] NULL,
[RecurrenceDayOfWeekMask] [int] NULL,
[RecurrenceDayOfMonth] [int] NULL,
[RecurrenceInstance] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceMonthOfYear] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceRegeneratedType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaskSubtype] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Task_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Task__copyloadda__5070F446] DEFAULT (getdate()),
[Old_TM_Activity__c] [bit] NULL,
[Close_Task__c] [bit] NULL,
[Left_Voicemail__c] [bit] NULL,
[Task_Completion_Date_Time__c] [datetime] NULL
)
GO
ALTER TABLE [prodcopystg].[Task] ADD CONSTRAINT [PK__Task__3214EC0777C908A2] PRIMARY KEY CLUSTERED  ([Id])
GO
