IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB QA Sec')
CREATE LOGIN [SSBINFO\SSB QA Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB QA Sec] FOR LOGIN [SSBINFO\SSB QA Sec]
GO
GRANT VIEW DEFINITION TO [SSBINFO\SSB QA Sec]
