IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB IE Sec')
CREATE LOGIN [SSBINFO\SSB IE Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB IE Sec] FOR LOGIN [SSBINFO\SSB IE Sec]
GO
GRANT SHOWPLAN TO [SSBINFO\SSB IE Sec]
GRANT VIEW DEFINITION TO [SSBINFO\SSB IE Sec]
